### ISSUE TITLE
Archive not being written to CWD

### ISSUE THREAD

**Issue by finanalyst** [frithnanth/perl6-Archive-Libarchive#12]
When using Archive::Libarchive with ArchiveOverwrite, the expectation is that the archive is written relative to the CurrentWorkingDirectory, not relative to the directory where the Raku program was called from. 

If it is a design decision to make the path of the Archive relative to the calling directory, and not `$*CWD`, may I suggest this is noted somewhere in the documentation.

Please see the following code
```
#!/usr/bin/env perl6
use v6.d;
use Archive::Libarchive;
use Archive::Libarchive::Constants;

my Archive::Libarchive $arc .= new(
    :operation(LibarchiveOverwrite),
    :file('cache.7z'),
);

my %h = <one two three four> Z=> 1..*;
# change to a sub-directory
my $orig = $*CWD;
chdir 'subdir';
my $b = Buf.new( %h.raku.encode );
say "Current dir: $*CWD";
try {
    $arc.write-header( 'some_name',
        :size($b.bytes),
        :atime(now.Int),
        :mtime(now.Int),
        :ctime(now.Int));
    $arc.write-data( $b );
    CATCH {
        default { .Str.say }
    }
}
$arc.close;
say 'finished';
$*CWD = $orig;
say 'listing of root: ', ('.'.IO.dir);
say 'listing of root/subdir: ', ('./subdir'.IO.dir);
```
which outputs
```
raku save-2-cache.raku 
Current dir: /home/richard/development/raku-collection/trial/subdir
finished
listing of root: ("get-from-cache.raku".IO "save-2-cache.raku".IO "cache.7z".IO "subdir".IO)
listing of root/subdir: ()
```

**Comment by frithnanth** [comment]
I had thought it as a security measure: in my opinion one shouldn't use a pathless file name.
OTOH you're right, the present behavior might surprise the user, so now I'm conflicted. I have to think about this because I can easily go either way, document the present state of the things, add `$*CWD` in front of the filename if it satisfies the condition `.dirname eq '.'`, or even add a `:follow-me` argument to the `.open` method to activate that behavior.

**Comment by frithnanth** [comment]
I decided to go for the note in the documentation.
Feel free to reopen this issue if you wish to add further notes, and thank you for raising the issue!
