### ISSUE TITLE
Error 90: No such entry found

### ISSUE THREAD

**Issue by ohmycloud** [frithnanth/perl6-Archive-Libarchive#7]
I have a `tar.gz` that contains two **txt** files, I try to print out the content of each file:

```perl6
my $a = Archive::Libarchive.new: operation => LibarchiveRead, file => $payload;

my $log-content = $a.read-file-content(sub (Archive::Libarchive::Entry $e --> Bool) { $e.pathname.ends-with('_log.txt')    });
my $res-content = $a.read-file-content(sub (Archive::Libarchive::Entry $e --> Bool) { $e.pathname.ends-with('_result.txt') });

say $log-content.decode('UTF8-C8'); #  ①
say $res-content.decode('UTF8-C8'); #  ②
```

step `①` print the content of  file that end with `_log.txt` ok .

but step `②` result in:

```
Error 90: No such entry found
```

if I comment the ` $log-content` line,  I can print out the content of  `_result.txt` :

```perl6
#  my $log-content = $a.read-file-content(sub (Archive::Libarchive::Entry $e --> Bool) { $e.pathname.ends-with('_log.txt')    }); # comment this 
my $res-content = $a.read-file-content(sub (Archive::Libarchive::Entry $e --> Bool) { $e.pathname.ends-with('_result.txt') }); # print out the content ok
```

**Comment by frithnanth** [comment]
The underlaying library doesn't allow random positioning, so if the second file you seek comes before the first, it's not found.
One easy workaround is to scan the archive (see `examples/list-file.p6`) in order to read the files according to their position in the archive.
I will give the problem some further thought: one possible solution is to feed the method with an array of desired files or closures and get an array of `Buf`s in return, another is to close and open the archive inside the method or in the calling program, but I wouldn't like this one.

**Comment by frithnanth** [comment]
There's a better way to do this after all, passing the entry to the method.
See the new version of `read-file-content` and the program `examples/readfile.p6`.

**Comment by ohmycloud** [comment]
💯 Thanks for your work
